### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#269]
@mcaceresb 	

I wanted to briefly lay out my plans about the future of the project, and figured an open issue would be a good place to do it.

My development will taper off and then end within the next three months; from late March to August I'm planning to hike the [Pacific Crest Trail](https://en.wikipedia.org/wiki/Pacific_Crest_Trail) (hoping to make it the entire way). After that, I'll almost certainly transition into a non-Econ job, and won't even have access to Stata.

Even in January-March, I'll have relatively little free time as I'll be heavily planning for the trail. My main goal for the short term then, is to make the program as stable as possible. I'm looking at:

- [ ] Adding lots of tests
- [x] Adding more documentation, especially creating an example Jupyter Notebook or two to show in the repository
- [ ] Possibly trying to fix the big linesize issue (#216, #177, #151). The core of this is that I search for the path of where the graph is saved to show a graph, but when the linesize is small and the path to the cache directory is long, it wraps lines and I don't catch the entire path.

Looking at the long term, I've already given @mcaceresb  write access to the repository. Especially after March, feel free (with no obligation) to improve the project however you see fit, including adding other contributors. I've written some [contributor documentation](https://github.com/kylebarron/stata_kernel/blob/master/CONTRIBUTING.md); do let me know if there's something you want me to add.

**Comment by mcaceresb** [comment]
Hey! Just getting around to these (vacation + sickness delayed me doing much). I think the three points you lay out do encapsulate the main things to work on. This is already very useful, even in corner cases where it trips up.

All the best on your trip!

**Comment by mcaceresb** [comment]
Hey! Just getting around to these (vacation + sickness delayed me doing much). I think the three points you lay out do encapsulate the main things to work on. This is already very useful, even in corner cases where it trips up.

All the best on your trip!
